name: AWS-BeanStalk-Pipeline

env:
  APP_S3_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  APP_NAME : "my-react-app"
  ENV_NAME: " my-react-app-dev"
  DEPLOY_PKG_NAME: "deploy-app_${{ github.sha }}.zip"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

on:
  push:
    branches: 
      - master


jobs:
  deployment:
    runs-on: [ubuntu-latest]
    
    steps:
     - name: Clone this repositary
       uses: actions/checkout@v1

     - name: Env variables
       run: echo "${{secrets.ENV_VAR }}" > .env

     - name: Make zip pkg
       run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*
       
     - name: Config Access to AWS
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_DEFAULT_REGION }}
     
     - name: push to S3
       run: aws s3 cp ${{ env.DEPLOY_PKG_NAME }} s3://${{ env.APP_S3_BUCKET_NAME }}/

     - name: Create new App Version
       run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.APP_NAME }} \
        --source-bundle S3Bucket="${{ env.APP_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PKG_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "SHA-${{ github.sha }}"
     - name: Deploy new App Version
       run : aws elasticbeanstalk update-environment --environment-name ${{ env.ENV_NAME }} --version-label "Ver-${{ github.sha }}"
